//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviseApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class projCat
    {
        public int projId { get; set; }
        public int catId { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isFinish { get; set; }
    
        public virtual category category { get; set; }
        public virtual project project { get; set; }
    }
}
